version: '3.8'

services:
  frontend:
    build: .
    image: dmolio/taskflow
    ports:
      - "3000:80"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secretpassword

volumes:
  mongodb_data:
