apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: taskflow
type: Opaque
data:
  MONGO_ROOT_USERNAME: YWRtaW4=  # admin
  MONGO_ROOT_PASSWORD: c2VjcmV0cGFzc3dvcmQ=  # secretpassword